const fs = require('fs');
const c = fs.readFileSync('public/report.html', 'utf8');
console.log('=== REPORT.HTML VERIFICATION ===');
console.log('CM - mgr.actual:', c.includes('mgr.actual'));
console.log('CM - mgr.node:', c.includes('mgr.node'));
console.log('CM - dot variable:', c.includes('const dot = ') || c.includes('const dot='));
console.log('CM - mgr.running (should be FALSE):', c.includes('mgr.running'));
console.log('CM - mDot (should be FALSE):', c.includes('mDot'));
console.log('OPP - opp.actual:', c.includes('opp.actual'));
console.log('OPP - opp.target:', c.includes('opp.target'));
console.log('OPP - opp.current_processes (should be FALSE):', c.includes('opp.current_processes'));
console.log('OPP - opp.target_processes (should be FALSE):', c.includes('opp.target_processes'));
console.log('WF - startup_mode:', c.includes('s.startup_mode'));
console.log('WF - DEACTIVATED_SYSTEM:', c.includes('DEACTIVATED_SYSTEM'));
console.log('WF - Startup Mode header:', c.includes('Startup Mode'));
console.log('OACore - placeholder:', c.includes('OACore (OA Framework) Heap') && !c.includes('oac.status') && !c.includes('if (oac)'));
console.log('Forms - placeholder:', c.includes('Forms Server</h3>') && !c.includes('if (frm)') && !c.includes('frm.status'));
console.log('Buttons - Detailed XLSX:', c.includes('Detailed XLSX'));
console.log('Buttons - Summary PDF:', c.includes('Summary PDF'));
console.log('m.actual in CM recommendation:', c.includes('m.target > 0 && m.actual < m.target'));